### ISSUE TITLE
WARNING when checking with WinBuilder

### ISSUE THREAD

**Issue by adamhsparks** [ropensci/getCRUCLdata#3]
I'm getting this error with both this and the _GSODR_ package when I check with WinBuilder. Everything seems fine but the rOpenSci footer.

> checking top-level files ... WARNING
> Conversion of 'README.md' failed:
> pandoc.exe: Could not fetch https://ropensci.org/public_images/github_footer.png
> TlsExceptionHostPort (HandshakeFailed Error_EOF) "ropensci.org" 443

@sckott, any ideas?

**Comment by sckott** [comment]
looks like we covered this in https://discuss.ropensci.org/t/warning-when-checking-with-winbuilder-and-or-kniting/745/2 already - sorry about the trouble with this

**Comment by adamhsparks** [comment]
Removed footer. This fixes the issue until pandoc updates are available.
