### ISSUE TITLE
how to run the get_CRU_df

### ISSUE THREAD

**Issue by sunjj878** [ropensci/getCRUCLdata#9]
Hi, could you tell me how to get_CRU_df?  I tried to use the code, but it seemed not to work.Thank you 

gth)
+                        frs = TRUE,    # ground-frost records (number of days with ground-frost per month)
+                        wnd = TRUE,    # 10m wind speed (m/s)
+                        elv = TRUE)    # elevation (and convert to m from km)
Error in get_CRU_df(pre = TRUE, pre_cv = TRUE, rd0 = TRUE, tmp = TRUE,  : 
  could not find function "get_CRU_df"

**Comment by adamhsparks** [comment]
Sorry, could you please provide a reproducible example? I'm not having any issues here.

```r
> library(getCRUCLdata)
> get_CRU_df(pre = TRUE)
             lat     lon month   pre
      1: -59.083 -26.583   jan 105.4
      2: -58.417 -26.250   jan 106.3
      3: -58.417 -26.417   jan 106.6
      4: -55.917 -67.250   jan  73.1
      5: -55.750 -67.250   jan  68.7
     ---                            
6795212:  83.583 -36.083   dec   0.1
6795213:  83.583 -36.250   dec   0.1
6795214:  83.583 -36.417   dec   0.1
6795215:  83.583 -36.583   dec   0.1
6795216:  83.583 -36.750   dec   0.1
```

**Comment by sunjj878** [comment]
Thanks, I have solved this problem. Have a good day!
